### ISSUE TITLE
Ошибки №1

### ISSUE THREAD

**Issue by galievruslan** [galievruslan/quattro#2]
1. Во всех вьювах edit, при редактировании любого объекта нажатием на button выдается ошибка типа No route matches [PUT] "/administration/services"
2. В форме регистрации на акции после каждого выбора (бренда/модели/тела) происходит перемещение в начало страницы

**Comment by golfarid** [comment]
По 1-му пункту синтаксис: <%= form_for [:administration, @service] do |f| %> (смотри пример во view _form контроллера administration_services)

**Comment by golfarid** [comment]
По второму пункту, проблема в href='#', исправил, но теперь необходимо поправить стили
